name: local
variables:
  - name: test_email
    value: admin@example.com
  - name: test_password
    value: Admin@123
  - name: jwt_token
    value: ""
  - name: baseURL
    value: http://localhost:4002/api
