version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: sql_practice
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_management
    ports:
      - "5433:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
