import { db } from '../db.js';
import * as Sentry from '@sentry/node';

/**
 * Simulated Lambda function that runs periodic inventory analytics.
 * In a real cloud environment, this would be a standalone AWS Lambda or similar.
 */
export async function runInventoryAnalytics() {
    console.log('📊 [Lambda: InventoryAnalytics] Starting daily report generation...');
    try {
        // 1. Calculate Total Sales
        const salesResult = await db.query(`
            SELECT 
                COUNT(*) as total_orders,
                SUM(CAST(item->>'price' AS DECIMAL)) as estimated_revenue
            FROM orders, jsonb_array_elements(items) as item
            WHERE status IN ('CONFIRMED', 'SHIPPED', 'DELIVERED')
        `);

        // Note: The revenue calculation above is simplified for the demo JSONB structure
        const { total_orders, estimated_revenue } = salesResult.rows[0];
        console.log(`📈 [Lambda: InventoryAnalytics] Total Successful Orders: ${total_orders}`);
        console.log(`💰 [Lambda: InventoryAnalytics] Estimated Revenue: $${estimated_revenue || 0}`);

        // 2. Identify Low Stock Items
        const lowStockResult = await db.query('SELECT title, stock FROM products WHERE stock < 5 AND stock > 0');
        if (lowStockResult.rows.length > 0) {
            console.warn(`⚠️ [Lambda: InventoryAnalytics] Found ${lowStockResult.rows.length} products with low stock!`);
            lowStockResult.rows.forEach(p => {
                console.warn(`   - ${p.title}: ${p.stock} units remaining`);
            });

            // Alert Sentry
            Sentry.captureMessage('Low stock alert generated by Analytics Lambda', {
                level: 'warning',
                extra: { products: lowStockResult.rows }
            });
        }

        // 3. Out of Stock Items
        const outOfStockResult = await db.query('SELECT title FROM products WHERE stock = 0');
        if (outOfStockResult.rows.length > 0) {
            console.error(`🚨 [Lambda: InventoryAnalytics] Found ${outOfStockResult.rows.length} products OUT OF STOCK!`);
        }

        console.log('✅ [Lambda: InventoryAnalytics] Analytics run completed.');
    } catch (err) {
        console.error('❌ [Lambda: InventoryAnalytics] Failed to run analytics:', err);
        Sentry.captureException(err);
    }
}
