services:
  temporal:
    container_name: temporal
    image: temporalio/admin-tools:latest
    ports:
      - "7233:7233"
      - "8080:8080"
    entrypoint: [ "temporal", "server", "start-dev", "--ip", "0.0.0.0", "--ui-port", "8080" ]
